// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/testproject_gg_1_version_test.dart.
// coverage:ignore-file

/// The version of the `testproject_gg_1` package.
const String testprojectGg1Version = '2.4.0';
